INSERT INTO roles (role_name) VALUES ('Administrator');
INSERT INTO roles (role_name) VALUES ('Moderator');
INSERT INTO roles (role_name) VALUES ('User');
INSERT INTO roles (role_name) VALUES ('Banned');

INSERT INTO users (role_id, user_name, user_login, user_password, user_email, user_date_registered) VALUES (1, 'Mark Kreyn', 'm.kreyn', SHA1('drp+72TuKr1sE52kMs'), 'm.kreyn@aol.com', NOW());

INSERT INTO users (role_id, user_name, user_login, user_password, user_email, user_date_registered) VALUES (4, 'Banned', 'banned', SHA1('banned'),'banned@banned.org', NOW() );

INSERT INTO permissions (permission_name) VALUES ('can_login');
INSERT INTO permissions (permission_name) VALUES ('can_access_admin');
INSERT INTO permissions (permission_name) VALUES ('can_add_recipe');
INSERT INTO permissions (permission_name) VALUES ('can_delete_recipe');
INSERT INTO permissions (permission_name) VALUES ('can_delete_any_recipe');
INSERT INTO permissions (permission_name) VALUES ('can_edit_recipe');
INSERT INTO permissions (permission_name) VALUES ('can_edit_any_recipe');
INSERT INTO permissions (permission_name) VALUES ('can_delete_bulk_recipe');
INSERT INTO permissions (permission_name) VALUES ('can_edit_bulk_recipe');
INSERT INTO permissions (permission_name) VALUES ('can_ban_users');
INSERT INTO permissions (permission_name) VALUES ('can_unban_users');
INSERT INTO permissions (permission_name) VALUES ('can_delete_users');
INSERT INTO permissions (permission_name) VALUES ('can_edit_profile');
INSERT INTO permissions (permission_name) VALUES ('can_edit_any_profile');

INSERT INTO cuisines (cuisine_name) VALUES ('Amish and Mennonite');
INSERT INTO cuisines (cuisine_name) VALUES ('Argentinian');
INSERT INTO cuisines (cuisine_name) VALUES ('Australian and New Zealander');
INSERT INTO cuisines (cuisine_name) VALUES ('Austrian');
INSERT INTO cuisines (cuisine_name) VALUES ('Bangladeshi');
INSERT INTO cuisines (cuisine_name) VALUES ('Belgian');
INSERT INTO cuisines (cuisine_name) VALUES ('Brazilian');
INSERT INTO cuisines (cuisine_name) VALUES ('Cajun and Creole');
INSERT INTO cuisines (cuisine_name) VALUES ('Canadian');
INSERT INTO cuisines (cuisine_name) VALUES ('Chilean');
INSERT INTO cuisines (cuisine_name) VALUES ('Chinese');
INSERT INTO cuisines (cuisine_name) VALUES ('Colombian');
INSERT INTO cuisines (cuisine_name) VALUES ('Cuban');
INSERT INTO cuisines (cuisine_name) VALUES ('Danish');
INSERT INTO cuisines (cuisine_name) VALUES ('Dutch');
INSERT INTO cuisines (cuisine_name) VALUES ('Filipino');
INSERT INTO cuisines (cuisine_name) VALUES ('Finnish');
INSERT INTO cuisines (cuisine_name) VALUES ('French');
INSERT INTO cuisines (cuisine_name) VALUES ('German');
INSERT INTO cuisines (cuisine_name) VALUES ('Greek');
INSERT INTO cuisines (cuisine_name) VALUES ('Indian');
INSERT INTO cuisines (cuisine_name) VALUES ('Indonesian');
INSERT INTO cuisines (cuisine_name) VALUES ('Israeli');
INSERT INTO cuisines (cuisine_name) VALUES ('Italian');
INSERT INTO cuisines (cuisine_name) VALUES ('Jamaican');
INSERT INTO cuisines (cuisine_name) VALUES ('Japanese');
INSERT INTO cuisines (cuisine_name) VALUES ('Jewish');
INSERT INTO cuisines (cuisine_name) VALUES ('Korean');
INSERT INTO cuisines (cuisine_name) VALUES ('Lebanese');
INSERT INTO cuisines (cuisine_name) VALUES ('Malaysian');
INSERT INTO cuisines (cuisine_name) VALUES ('Mexican');
INSERT INTO cuisines (cuisine_name) VALUES ('Norwegian');
INSERT INTO cuisines (cuisine_name) VALUES ('Pakistani');
INSERT INTO cuisines (cuisine_name) VALUES ('Persian');
INSERT INTO cuisines (cuisine_name) VALUES ('Peruvian');
INSERT INTO cuisines (cuisine_name) VALUES ('Polish');
INSERT INTO cuisines (cuisine_name) VALUES ('Portuguese');
INSERT INTO cuisines (cuisine_name) VALUES ('Puerto Rican');
INSERT INTO cuisines (cuisine_name) VALUES ('Russian');
INSERT INTO cuisines (cuisine_name) VALUES ('Scandinavian');
INSERT INTO cuisines (cuisine_name) VALUES ('Soul Food');
INSERT INTO cuisines (cuisine_name) VALUES ('South African');
INSERT INTO cuisines (cuisine_name) VALUES ('Southern Recipes');
INSERT INTO cuisines (cuisine_name) VALUES ('Spanish');
INSERT INTO cuisines (cuisine_name) VALUES ('Swedish');
INSERT INTO cuisines (cuisine_name) VALUES ('Swiss');
INSERT INTO cuisines (cuisine_name) VALUES ('Tex-Mex');
INSERT INTO cuisines (cuisine_name) VALUES ('Turkish');
INSERT INTO cuisines (cuisine_name) VALUES ('Vietnamese');

INSERT INTO recipe_ingredients (ingredient) VALUES ('Almond Meal');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Almonds');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Amaranth');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Apples');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Apricots');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Avocados');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Bananas');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Barley');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Beef');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Beef Chuck');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Beef Ribs');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Beef Tenderloin');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Brisket');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Brown Rice');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Buckwheat');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Bulgur');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Cheese');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Cherries');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Chia Seeds');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Chicken');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Chicken Breasts');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Chicken Legs');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Chicken Thighs');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Chicken Wings');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Chocolate');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Coconut');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Corn Flour');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Cornish Hens');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Cornmeal');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Duck');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Fish');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Flax Seeds');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Goat');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Ground Beef');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Ground Chicken');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Ground Pork');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Ground Turkey');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Lamb');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Mangos');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Millet');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Mushroom');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Nectarines');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Oat Flour');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Oats');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Peaches');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Peanuts');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Pears');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Pineapples');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Plums');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Pomegranates');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Pork');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Pork Ribs');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Pork Shoulder');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Pork Tenderloin');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Prime Rib');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Quinoa');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Sausage');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Seafood');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Shellfish');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Sirloin');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Spelt');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Steak');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Tapioca Flour');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Turkey');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Veal');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Venison');
INSERT INTO recipe_ingredients (ingredient) VALUES ('White Rice Flour');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Wild Game');
INSERT INTO recipe_ingredients (ingredient) VALUES ('Wild Rice');

INSERT INTO recipe_levels (level_name) VALUES ('Beginner');
INSERT INTO recipe_levels (level_name) VALUES ('Pre-intermediate');
INSERT INTO recipe_levels (level_name) VALUES ('Intermediate');
INSERT INTO recipe_levels (level_name) VALUES ('Upper-intermediate');
INSERT INTO recipe_levels (level_name) VALUES ('Advanced');
INSERT INTO recipe_levels (level_name) VALUES ('Profy');
INSERT INTO recipe_levels (level_name) VALUES ('Expert');
INSERT INTO recipe_levels (level_name) VALUES ('God');

INSERT INTO recipe_categories (category_name) VALUES ('Vegetable recipes');
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Artichoke recipes' FROM recipe_categories WHERE category_name = 'Vegetable recipes';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Asparagus recipes' FROM recipe_categories WHERE category_name = 'Vegetable recipes';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Beet recipes' FROM recipe_categories WHERE category_name = 'Vegetable recipes';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Brussels sprouts recipes' FROM recipe_categories WHERE category_name = 'Vegetable recipes';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Corn recipes' FROM recipe_categories WHERE category_name = 'Vegetable recipes';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Cucumber recipes' FROM recipe_categories WHERE category_name = 'Vegetable recipes';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Eggplant recipes' FROM recipe_categories WHERE category_name = 'Vegetable recipes';

INSERT INTO recipe_categories (category_name) VALUES ('Sweet');
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Cakes' FROM recipe_categories WHERE category_name = 'Sweet';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Candies' FROM recipe_categories WHERE category_name = 'Sweet';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Cheesecakes' FROM recipe_categories WHERE category_name = 'Sweet';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Cupcakes' FROM recipe_categories WHERE category_name = 'Sweet';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Muffins' FROM recipe_categories WHERE category_name = 'Sweet';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Cookies' FROM recipe_categories WHERE category_name = 'Sweet';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Desserts' FROM recipe_categories WHERE category_name = 'Sweet';
INSERT INTO recipe_categories (parent_id, category_name) SELECT id, 'Pies' FROM recipe_categories WHERE category_name = 'Sweet';

